increment 13 is completed
kupriyanovkk/shortener pull request #13
Opened 2023-10-17 15:21 UTC by kupriyanovkk

2023-10-18 08:52 UTC, gonozov0 requested changes
Отличная работа 👍
Как и всегда круто, что код только по делу, легко воспринимать и читать
Но есть проблема с реализацией Storage, важно чтобы DBStorage был отдельной структурой, которая соответствует интерфейсу Storage (подробности в комменте к ревью)

2023-10-18 08:52 UTC, gonozov0 commented on internal/server/server.go
> +package server
Довольно массивный файл получается. У тебя в этом пакете по сути лежат хендлеры, я бы переименовал пакет в handlers и разбил бы каждый handler на отдельный файл

2023-10-18 08:52 UTC, gonozov0 commented on internal/storage/storage.go
> +	case DataBaseStorage:
Для реализации storage для базы такой подход точно нам не подойдет.

Нам необходимо разработать отдельную структуру DBStorage (или PgStorage, не суть), но отдельную, которая будет соответствовать интерфейсу Storage (почему то его теперь даже не вижу).

Текущую структуру Storage по сути необходимо переименовать в MemoryStorage, а в хендлерах использовать интерфейс Storage.

Если сложно и непонятно, что я сейчас тут написал, то запланируй плиз 1:1 на этой неделе (т.к. потом я в отпуске) или напиши в личку, возможно даже сегодня получится.
Расскажу поподробнее

2023-10-19 08:50 UTC, kupriyanovkk commented on internal/server/server.go
> +package server
Переписал

2023-10-19 08:50 UTC, kupriyanovkk commented on internal/storage/storage.go
> +	case DataBaseStorage:
Сделал рефакторинг

2023-10-19 13:11 UTC, gonozov0 approved these changes
Отлично, все моменты поправлены

2023-10-23 21:06 UTC, merged