increment 18 is completed
kupriyanovkk/shortener pull request #18
Opened 2023-12-28 15:27 UTC by kupriyanovkk

2023-12-29 12:35 UTC, gonozov0 requested changes
Отличная работа 👍
Внес много улучшений по документации, а также написал бенчмарк
Оставил пару комментариев по коду
Так же подскажи плиз, удалось ли разобраться с pprof? Посмотреть визуально, какие части твоего кода дольше всего выполняются и занимают памяти.
Спрашиваю потому, что пообщавшись на 1:1 у многих не сложилось полное понимание, как он работает
https://app.pachca.com/chats?thread_id=2568500&sidebar_message=112734394

2023-12-29 12:35 UTC, gonozov0 commented on profiles/base.pprof
Скорее всего случайно закоммитил
Бинарники не должны попадать в репозиторий, лучше в Readme или makefile расписать логику, как их локально, если нужно, получить

2023-12-29 12:35 UTC, gonozov0 commented on profiles/result.pprof
аналогично

2023-12-29 12:35 UTC, gonozov0 commented on internal/models/models.go
> +}
Почему решил сюда перенести?
На мой взгляд в models.go интерфейсы точно не должны лежать

На практике используют 2 подхода для размещения интерфейсов:
1. Рядом с реализацией, обычно файл называют interface.go (практически как у тебя и было)
2. Рядом с местом использования (в хендлерах, слое бизнес логики). В этом случае интерфейсов может быть несколько и с меньшим количеством методов под каждое место использования

2024-01-03 13:36 UTC, kupriyanovkk commented on profiles/base.pprof
Думал по заданию нужно закоммитить :)

2024-01-03 14:09 UTC, kupriyanovkk commented on internal/models/models.go
> +}
Переделал

2024-01-04 07:50 UTC, gonozov0 approved these changes
Работа принята 👍
Все моменты поправлены

2024-01-06 13:58 UTC, merged