increment 23 is completed
kupriyanovkk/shortener pull request #23
Opened 2024-01-30 19:49 UTC by kupriyanovkk

2024-02-01 09:18 UTC, gonozov0 requested changes
Отличная работа 👍
Лаконично реализовал tls и особенно круто, что не забыл про тесты
Оставил пару комментариев по улучшению кода

2024-02-01 09:18 UTC, gonozov0 commented on internal/app/app.go
> +	signal.Notify(sigint, syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
Тут лучше использовать NotifyContext

2024-02-01 09:18 UTC, gonozov0 commented on internal/app/app.go
> +	idleConnsClosed := make(chan struct{})
Для этого лучше использовать WaitGroup, и в горутине надежнее будет вызывать wg.Done через defer

2024-02-05 07:53 UTC, gonozov0 requested changes
Только сейчас заметил, что одна из горутин не завершается graceful
Если нет понимания, как правильно сделать, можем сегодня в пн вечером 1:1 провести, напиши в личку плиз для этого
Также если есть какие-то проблемы с дедлайнами/временем, то тоже напиши в личку, решим

2024-02-05 07:53 UTC, gonozov0 commented on internal/app/app.go
>  	go handlers.FlushDeletedURLs(app)
Сорри, не заметил раньше, но нужно чтобы все горутины graceful завершались, соответственно и эта тоже.
Тебе придется, как минимум NotifyContext и WaitGroup вынести на этот уровень

2024-02-06 09:54 UTC, kupriyanovkk commented on internal/app/app.go
>  	go handlers.FlushDeletedURLs(app)
Переделал

2024-02-07 07:58 UTC, gonozov0 approved these changes
Апрув 👍

2024-02-08 05:54 UTC, merged